# Generated by Django 2.2.3 on 2019-09-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerimonia',
            name='dataFim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cerimonia',
            name='dataInicio',
            field=models.CharField(max_length=100),
        ),
    ]
