# Generated by Django 2.2.3 on 2019-09-22 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0002_auto_20190918_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigOauthGitLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APP_ID', models.TextField()),
                ('REDIRECT_URI', models.TextField()),
                ('your_unique_state_hash', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ConfigOauthGitLab',
            },
        ),
    ]
