# Generated by Django 2.2.3 on 2019-09-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0003_configoauthgitlab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configoauthgitlab',
            old_name='APP_ID',
            new_name='app_id',
        ),
        migrations.RenameField(
            model_name='configoauthgitlab',
            old_name='REDIRECT_URI',
            new_name='app_secret',
        ),
        migrations.RenameField(
            model_name='configoauthgitlab',
            old_name='your_unique_state_hash',
            new_name='redirect',
        ),
    ]
