# Generated by Django 2.2.6 on 2019-10-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0005_auto_20191007_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigOauthGitLab',
        ),
        migrations.AlterField(
            model_name='cerimonia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='convite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
